import {
  Brain,
  Heart,
  Star,
  Smile,
  Trophy,
  Target,
  Users,
  Sparkles,
  Lightbulb,
  Palette,
  Music,
  BookOpen,
  Speech,
  HandHeart,
  Puzzle,
  Shapes,
  Gauge,
  Timer,
  Calendar,
  ListTodo,
  Scale,
  Compass,
  Mountain,
  Footprints,
  Glasses,
  Leaf,
  Flame,
  Zap,
  Crown,
  Medal
} from 'lucide-react';

export const skillIcons = {
  Brain: { icon: Brain, category: 'Cognitive' },
  Heart: { icon: Heart, category: 'Emotional' },
  Star: { icon: Star, category: 'Achievement' },
  Smile: { icon: Smile, category: 'Social' },
  Trophy: { icon: Trophy, category: 'Achievement' },
  Target: { icon: Target, category: 'Goals' },
  Users: { icon: Users, category: 'Social' },
  Sparkles: { icon: Sparkles, category: 'Creative' },
  Lightbulb: { icon: Lightbulb, category: 'Ideas' },
  Palette: { icon: Palette, category: 'Creative' },
  Music: { icon: Music, category: 'Arts' },
  BookOpen: { icon: BookOpen, category: 'Learning' },
  Speech: { icon: Speech, category: 'Communication' },
  HandHeart: { icon: HandHeart, category: 'Empathy' },
  Puzzle: { icon: Puzzle, category: 'Problem Solving' },
  Shapes: { icon: Shapes, category: 'Organization' },
  Gauge: { icon: Gauge, category: 'Performance' },
  Timer: { icon: Timer, category: 'Time Management' },
  Calendar: { icon: Calendar, category: 'Planning' },
  ListTodo: { icon: ListTodo, category: 'Organization' },
  Scale: { icon: Scale, category: 'Balance' },
  Compass: { icon: Compass, category: 'Direction' },
  Mountain: { icon: Mountain, category: 'Growth' },
  Footprints: { icon: Footprints, category: 'Progress' },
  Glasses: { icon: Glasses, category: 'Focus' },
  Leaf: { icon: Leaf, category: 'Growth' },
  Flame: { icon: Flame, category: 'Passion' },
  Zap: { icon: Zap, category: 'Energy' },
  Crown: { icon: Crown, category: 'Leadership' },
  Medal: { icon: Medal, category: 'Achievement' }
};

export type SkillIconName = keyof typeof skillIcons;